# 絶対に書き換えないでください。
configVersion: '1.1'

# 許可するドメインのリスト
domainList:
  - 'mc.example.com'
  - 'play.example.com'

# ドメインが一致しない場合の処理 [allow, allow-logging, kick, kick-logging]
# allow: 何もせず許可
# allow-logging: ログインを許可し、プレイヤーとドメインをログに記録
# kick: ログインをキャンセル
# kick-logging: ログインをキャンセルし、プレイヤーとドメインをログに記録
unmatchedDomainAction: 'kick-logging'

kickMessage:
  - '使用できないドメインです。'
  - 'Unavailable domains.'