# your domain
domainList:
  - 'mc.example.com'
  - 'play.example.com'

# ドメインが一致しない場合の処理 [allow, kick, kickLogging]
# allow: 何もせず許可
# kick: ログインをキャンセル
# kickLogging: ログインをキャンセルし、プレイヤーとドメインをログに記録
unmatchedDomainAction: 'kickLogging'

kickMessage:
  - '使用できないドメインです。'
  - 'Unavailable domains.'